### ISSUE TITLE
Container fails to stay running on second and subsequent starts

### ISSUE THREAD

**Issue by SoulGit** [scline/docker-cacti#38]
Terminal / log: 

`AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.6. Set the 'ServerName' directive globally to suppress this message `

And the container stops.  I have temporarily added the following to start.sh to remediate, although might be best to add to Dockerfile on initial build?

echo "ServerName localhost" > /etc/httpd/conf.d/fqdn.conf

**Comment by scline** [comment]
I need to update the cacti versions this week and will add this to the dockerfile as you suggested. Thanks for pointing this out!
