### ISSUE TITLE
Where is crontab.apache file mentioned in documentation?

### ISSUE THREAD

**Issue by SoulGit** [scline/docker-cacti#40]
Documentation suggests it should be in the config directory.

**Comment by scline** [comment]
Looks like that is poor documentation on my part and will update/re-word this. Today the cron file is simply under `config/crontab`. I believe the apache reference was me testing things in the lab that never made it out due to it not working.

**Comment by scline** [comment]
This is resolved in https://github.com/scline/docker-cacti/pull/41, removed the documentation references for now. Thanks for the followup on this (^_^)!
