### ISSUE TITLE
Cacti breaks if container is recreated

### ISSUE THREAD

**Issue by shortbloke** [scline/docker-cacti#44]
Issues: Some setting which need to persist are being retained within the container, such that a container can not be re-created. This seems pretty fundamental, unless I'm missing something (sorry a bit new to Docker).

Reproduction Steps:
- Copy cacti_single_install.yml to docker-compose.yaml
- Edit docker-compose.yaml to change the ports which are in use (as 80 and 443 are already in use)
```
    ports:
      - "8282:80"
      - "8383:443"
```
- Run `docker-compose up -d` to create the cacti and database containers
- Open localhost:8282 and complete the configuration of cacti
- Make a change to the `docker-compose.yml` file. .e.g. Change the port again to say 8080 for cacti, or change the timezone, or add some additional labels (for example adding Traefik support).
- Re-run `docker-compose up -d` the cacti_cacti_1 container will be recreated.
- Navigate to localhost:8080 (if you changed the port) find you now get the Apache HTTP Server Test page, not Cacti. http://localhost:8080/cacti gives error not found.

**Comment by scline** [comment]
Thank you for the report, offhand I am not sure if this is expected or not with Docker workflows but will investigate this more in depth and if there is anything we can do to resolve this.

**Comment by scline** [comment]
This issue is fixed in #54
