### ISSUE TITLE
Directories backup and backups mixed up

### ISSUE THREAD

**Issue by shortbloke** [scline/docker-cacti#45]
The backup script copies the resultant backup .tar.gz file to /backup however readme indicates it should be /backups
The docker-compose files also map /backups which then doesn't work as the backups are created within the container not in the mapped volume. 

I'd submit changes, but I'm not sure if you'd prefer backup or backups to be used. It does contain multiple so the plural would make more sense. This would need the backup.sh to be updated and the readme.

**Comment by shortbloke** [comment]
I've created a suggested PR, in case that helps.

**Comment by scline** [comment]
Closing since you created a PR that was merged, thank you!
