### ISSUE TITLE
errors with percona on compose single instance

### ISSUE THREAD

**Issue by miguelwill** [scline/docker-cacti#59]
good
when using the example with the compose using the suggested database, the installation process cannot create the "poller_output_boost" table due to an error with the timestamp format of the "time" field
I changed the image percona to mariadb:10.3, and this succeeded in creating the table without problems

**Comment by scline** [comment]
I will update those examples over the next week or so (whenever I get to merging this new branch). 

Thank you very much for pointing that out!

**Comment by scline** [comment]
This has been updated in the docker-compose examples, thanks for the report 👍
