### ISSUE TITLE
no listening sockets available, shutting down

### ISSUE THREAD

**Issue by luelco** [scline/docker-cacti#77]
Hi Guys,

I'm new to docker so sorry for the odd questions.

I want to launch a container on my Synology device. But when I choose "Use the same network as Docker Host" I cannot change the port settings. I think this is the reason that I'm getting the following error's:

(98)Address already in use: AH00072: make_sock: could not bind to address [::]:80 
(98)Address already in use: AH00072: make_sock: could not bind to address 0.0.0.0:80 
no listening sockets available, shutting down 
AH00015: Unable to open logs

Is it also possible to add port as a variable in the Advanced Settings? Or do I have anyother options?

**Comment by scline** [comment]
Sorry I am not familiar with Synology, a glance at there documentation that option does appear to be what you need
![image](https://user-images.githubusercontent.com/4343127/94345720-f534fd00-ffdc-11ea-90f8-934b122c62d5.png)


Should be something like:
**HTTP**
Local Port: 80 <---- Change this to something else, ex 8080
Container Port: 80
Type: TCP

**HTTPS**
Local Port: 443 <---- Change this to something else, ex 8443
Container Port: 443
Type: TCP


From that log your Synology likely is using port 80/443 to run its services and you cant attach two applications to a single port.

**Comment by luelco** [comment]
Thank you for your reply, but when you choose "Use the same network as Docker Host" you can't change the port settings. 
![Capture](https://user-images.githubusercontent.com/71927085/94346618-22f66200-002e-11eb-8e7e-b420345ad209.JPG)

**Comment by luelco** [comment]
Sorry for the misunderstanding, is it also possible to add port as a **Environment** variable in the Advanced Settings?

**Comment by luelco** [comment]
Hi All, 
I managed to Free up port 80/443 on Synology DSM. So now this is no issue anymore.
But now the container freeze at HTTPD service. 

I notice that someone else had this issue also and this was solved with option -d. I guess this was done on the CLI. What does this do and can I add this option to the GUI?

**Comment by luelco** [comment]
Hi scline,

You can close this issue. My issue is now the HTTPD service.
