### ISSUE TITLE
How to add perl package

### ISSUE THREAD

**Issue by zgodzgod** [scline/docker-cacti#86]
How to add perl package for cacti container: perl-libwww-perl?
Can you give me some suggestions?

**Comment by scline** [comment]
There are a few ways to add that package. You can edit the Dockerfile to include the package or manually install it once the container is running.

https://docs.docker.com/engine/reference/commandline/exec/

```
docker exec -ti <cacti_container_id> bash
[root@cacti /]# yum install perl-libwww-perl
```

You can also bake it into the base container by adding the yum install command to the DockerFile like https://github.com/scline/docker-cacti/pull/87/files

Will see about merging that tonight if no issues pop up so you can simply pull latest or 1.2.16a to automatically have that package :)

**Comment by scline** [comment]
It's now in the `latest` tag, be sure to re-pull the docker container to grab the new version

```
[root@cacti /]# rpm -q perl-libwww-perl
perl-libwww-perl-6.34-1.module_el8.3.0+416+dee7bcef.noarch
```
